from types import CodeType

# sys.monitoring callbacks. The code object is always the first argument; any
# further event-specific arguments (offset, retval, exception) are ignored.
def _on_entry(code: CodeType, /, *args: object) -> None: ...
def _on_exit(code: CodeType, /, *args: object) -> None: ...

# Tracy frame marks. Names are interned into persistent C copies (Tracy stores
# the pointer), so passing the same name repeatedly is cheap.
def frame_mark(name: str | None = None, /) -> None: ...
def frame_mark_start(name: str, /) -> None: ...
def frame_mark_end(name: str, /) -> None: ...
